### PR TITLE
Some Darwin code fixes

### PR DESCRIPTION
**Pull request by badboy**
Hi, I've been building on top of your fork in the recent weeks (and [built a Hare playground](https://fnordig.de/2024/06/04/playground-for-hare/) and had to fix a couple of things.

### CODE REVIEW

**Comment by hshq** [comment]
我不认为 `bind` 等系统调用有必要使用 `int` 作为表示 **成功** 的返回值类型。
`void` 足够了，`int` 反而让人困扰结果是否有其他可能性；
而且它们的调用处最终仍然是把 `int` 转为 `void`。
我感觉这种方式更自然，而不是用 **C 语言** 的方式写 **hare 语言** 。   

I don't think it's necessary for system calls like `bind` to use `int` as the return value type to indicate **success**.
`void` is enough, and `int` makes people confused whether there are other possibilities for the result;
And the place where they are called still converts `int` to `void` in the end.
I feel that this method is more natural, rather than writing **hare language** in **C language** way.

**Comment by badboy** [comment]
> 我不认为 `bind` 等系统调用有必要使用 `int` 作为表示 **成功** 的返回值类型。 `void` 足够了，`int` 反而让人困扰结果是否有其他可能性； 而且它们的调用处最终仍然是把 `int` 转为 `void`。 我感觉这种方式更自然，而不是用 **C 语言** 的方式写 **hare 语言** 。
> 
> I don't think it's necessary for system calls like `bind` to use `int` as the return value type to indicate **success**. `void` is enough, and `int` makes people confused whether there are other possibilities for the result; And the place where they are called still converts `int` to `void` in the end. I feel that this method is more natural, rather than writing **hare language** in **C language** way.

I ran into some problems where the `void` return however did cause a problem. I can try to reproduce to make that more clear (plus the Linux/BSD code returns `int` there too, and I felt having it consistent with upstream code would make things easier in the long term. )

**Comment by badboy** [comment]
fwiw I'd be fine splitting the return type changes out though, the socket types and the pipe2 change are actual bugs causing issues.

**Comment by hshq** [comment]
好的，那么分开处理吧。

Okay, then let's handle it separately.

**Comment by badboy** [comment]
Alright, I redid it. The `int` returns where indeed not the problem. But I made one fix more clear: `socket` doesn't accept flags. While I was at it I fixed the return values up to `void` on a few more.

**Comment by hshq** [comment]
我看到 Mac 上并没有 `SOCK_CLOEXEC` 和 `SOCK_NONBLOCK`，
是否简单地把他们定义为 `0` 能解决你遇到的问题？
若如此，则无须更改大多数与它们相关的代码。

I see that there are no `SOCK_CLOEXEC` and `SOCK_NONBLOCK` on Mac,
Can you simply define them a `0` to solve the problems you encounter?
If so, there is no need to change most of the code related to them.

**Pull request merged**
